### ISSUE TITLE
Received error running ternimal

### ISSUE THREAD

**Issue by vuongfunny** [katalon-studio/katalon-recorder-helper#2]
Description:

The Tomcat connector configured to listen on port 18910 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 18910, or configure this application to listen on another port.

**Comment by devalex88** [comment]
Thank you for your bug report. We will consider the possibility to change the server port in the future.
